### PR TITLE
Honour comment indent for "elif" or "else" block

### PR DESCRIPTION
**Pull request by kyeongy**
It is usual to add comment lines before "elif" or "else". So keep the indent
as is if the comment line is indented to the same column with "elif"/"else".

```bash
f()
{
  if [ ... ]; then
    echo a
    # comment 1
  elif [ ... ]; then
    echo b
  # comment 2 <-- keep this
  elif [ ... ]; then
    echo c
  # comment 3 <-- keep this
  else [ ... ]; then
    echo d
  fi
}
```

### CODE REVIEW

**Comment by bergwerf** [comment]
Looks good!
Some things that have to be done before merging/publishing this:
1. Update dependencies in `setup.py` (I could do this later)
2. Check if argparse is backwards compatible with the previous piping behaviour

**Comment by bergwerf** [comment]
Your changes look mostly like some ad hoc solutions. But I think that is acceptable as I don't have time to propose a cleaner solution either. I'll try to look at the two mentioned things somewhere this week hopefully.

**Comment by kyeongy** [comment]
Thanks.
I've check "-" works as before so you can double check.

Yes the comment handling seems not much tidy but I've been thinking several days but couldn't find better idea. Obviously it's not a fix to be in immediately.

**Comment by kyeongy** [comment]
Any progress on my patches? Waiting for a new version!

**Comment by bergwerf** [comment]
Sorry, was busy. Have this planned for this weekend.

**Comment by bergwerf** [comment]
Version 0.1.6 is now on PyPI. Thanks for your contribution :-)

**Pull request merged**
